imports:

services:
  mollie:
    class: 'Mollie'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mollie'

  Mollie\Service\OrderFeeService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\PaymentMethodService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\ApiService:
    arguments:
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Repository\CountryRepository'

  Mollie\Service\ConfigFieldService:
    arguments:
      - '@mollie'
      - '@Mollie\Service\ApiService'
      - '@Mollie\Repository\CountryRepository'

  Mollie\Service\RefundService:
    arguments:
      - '@mollie'

  Mollie\Service\ShipService:
    arguments:
      - '@mollie'

  Mollie\Service\CancelService:
    arguments:
      - '@mollie'

  Mollie\Service\CarrierService:

  Mollie\Service\OrderStatusService:

  Mollie\Service\CountryService:
    arguments:
      - '@mollie'

  Mollie\Service\SettingsSaveService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\CountryRepository'
      - '@Mollie\Repository\PaymentMethodRepository'
      - '@Mollie\Service\PaymentMethodService'
      - '@Mollie\Service\ApiService'

  Mollie\Repository\PaymentMethodRepository:

  Mollie\Repository\OrderFeeRepository:

  Mollie\Repository\CountryRepository:

  Mollie\Repository\OrderShipmentRepository:

  Mollie\Utility\LanguageUtility:
    arguments:
      - '@mollie'

  Mollie\Install\Installer:
    arguments:
      - '@mollie'

  Mollie\Install\Uninstall:
    arguments:
      - '@mollie'