imports:

services:
  mollie:
    class: 'Mollie'
    factory: ['Module', 'getInstanceByName']
    arguments:
      - 'mollie'

  Mollie\Service\OrderFeeService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\PaymentMethodService:
    arguments:
      - '@mollie'
      - '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Service\ApiService:

  Mollie\Repository\PaymentMethodRepository:

  Mollie\Repository\OrderFeeRepository:

  Mollie\Utility\LanguageUtility:
    arguments:
      - '@mollie'