services:
  Mollie\Handler\Settings\PaymentMethodPositionHandler:
    arguments:
      - '@Mollie\Repository\PaymentMethodRepositoryInterface'

  Mollie\Handler\Settings\PaymentMethodPositionHandlerInterface: '@Mollie\Handler\Settings\PaymentMethodPositionHandler'

  Mollie\Handler\Exception\OrderExceptionHandler:

  Mollie\Handler\Api\OrderEndpointPaymentTypeHandler:
    class: Mollie\Handler\Api\OrderEndpointPaymentTypeHandler
    arguments:
      - '@Mollie\Verification\PaymentType\CanBeRegularPaymentType'

  Mollie\Handler\Shipment\ShipmentSenderHandler:
    class: Mollie\Handler\Shipment\ShipmentSenderHandler
    arguments:
      - '@Mollie\Verification\Shipment\CanSendShipment'
      - '@Mollie\Service\Shipment\ShipmentInformationSender'
      - '@Mollie\Service\ExceptionService'
      - '@Mollie\Logger\PrestaLogger'

  Mollie\Handler\Shipment\ShipmentSenderHandlerInterface: '@Mollie\Handler\Shipment\ShipmentSenderHandler'
