services:
  Mollie\Provider\CreditCardLogoProvider:
    arguments:
      - '@=service("mollie.factory.module_factory").getLocalPath()'
      - '@=service("mollie.factory.module_factory").getPathUri()'

  Mollie\Service\PaymentMethod\PaymentMethodSortProvider:

  Mollie\Provider\PhoneNumberProvider:

  Mollie\Provider\OrderState\OrderStateAutomaticShipmentSenderStatusesProvider:
    class: Mollie\Provider\OrderState\OrderStateAutomaticShipmentSenderStatusesProvider
    arguments:
      - '@Mollie\Adapter\ConfigurationAdapter'
