services:
  Mollie\Provider\CreditCardLogoProvider:
    arguments:
      - '@=service("mollie.factory.module_factory").getLocalPath()'
      - '@=service("mollie.factory.module_factory").getPathUri()'

  Mollie\Service\PaymentMethod\PaymentMethodSortProvider:

  Mollie\Provider\PhoneNumberProvider:

  Mollie\Provider\PaymentMethod\PaymentMethodCurrencyProvider:
    class: Mollie\Provider\PaymentMethod\PaymentMethodCurrencyProvider

  Mollie\Provider\PaymentMethod\PaymentMethodCountryProvider:
    class: Mollie\Provider\PaymentMethod\PaymentMethodCountryProvider