services:
#  @deprecated - dont call repositories directly, use interface instead
  Mollie\Repository\PaymentMethodRepository:

  Mollie\Repository\PaymentMethodRepositoryInterface: '@Mollie\Repository\PaymentMethodRepository'

  Mollie\Repository\OrderFeeRepository:

  Mollie\Repository\CountryRepository:

  Mollie\Repository\OrderShipmentRepository:

  Mollie\Repository\MethodCountryRepository:

  Mollie\Repository\MolCarrierInformationRepository:

  Mollie\Repository\ModuleRepository:

  Mollie\Repository\PendingOrderCartRepository:
    arguments:
      - 'MolPendingOrderCart'

  Mollie\Repository\MolCustomerRepository:
    arguments:
      - 'MolCustomer'

  Mollie\Repository\AttributeRepository:

  Mollie\Repository\OrderStateRepository:

  Mollie\Repository\OrderRepository:
    class: Mollie\Repository\OrderRepository
    arguments:
      - 'Order'

  Mollie\Repository\OrderCartRuleRepository:
    class: Mollie\Repository\OrderCartRuleRepository
    arguments:
      - 'OrderCartRule'

  Mollie\Repository\CartRuleRepository:
    class: Mollie\Repository\CartRuleRepository
    arguments:
      - 'CartRule'

  Mollie\Repository\PendingOrderCartRuleRepository:
    class: Mollie\Repository\PendingOrderCartRuleRepository
    arguments:
      - 'MolPendingOrderCartRule'