name: Tests

on: [pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MOLLIE_TESTS}}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

  phpunit:
    name: PHPUNIT
    runs-on: ubuntu-latest
    steps:
      - name: checkout project
        uses: actions/checkout@v2

      - name: composer install missing files
        run: composer install

      - name: PHPUnit tests
        uses: php-actions/phpunit@v1
        with:
          bootstrap: ./bootstrap.php
          configuration: ./phpunit.xml
          memory_limit: 256M

#  test:
#    name: Unit tests
#    runs-on: ubuntu-latest
#
#    steps:
#      -   name: Checkout
#          uses: actions/checkout@v2.0.0
#
#      -   name: Pull PrestaShop files (Tag ${{ matrix.presta-versions }})
#          run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.7.0
#
#      -   name: Run PHPunit tests
#          run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module  php web/module/tests/phpunit.phar web/module/tests/Unit/ --bootstrap=/web/module/tests/Unit/bootstrap.php

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['1.7.6.8', '1.6.1.23', '1.7.7.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Pull PrestaShop files (Tag ${{ matrix.presta-versions }})
        run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:${{ matrix.presta-versions }}

      - name : Run PHPStan
        run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module phpstan/phpstan:0.12 analyse --configuration=/web/module/tests/phpstan/phpstan${{ matrix.presta-versions }}.neon --debug --error-format github
