name: Tests

on: [push, pull_request]

jobs:
  test:

    runs-on: ubuntu-latest

#    strategy:
#      matrix:
#        php-version: [5.6, 7.0, 7.1, 7.2]
      
    steps:
    - uses: actions/checkout@v2

    - name: Validate composer.json and composer.lock
      run: composer validate

    - name: Cache Composer packages
      id: composer-cache
      uses: actions/cache@v2
      with:
        path: vendor
        key: ${{ runner.os }}-php-${{ hashFiles('**/composer.lock') }}
        restore-keys: |
          ${{ runner.os }}-php-

#    - name: Use php-version ${{ matrix.php-version }}
#      uses: actions/setup-php@v1
#      with:
#        php-version: ${{ matrix.php-version }}
        
    - run: composer require --dev phpunit/phpunit ^5
    - run: ./vendor/bin/phpunit tests/Unit
        
    # Add a test script to composer.json, for instance: "test": "vendor/bin/phpunit"
    # Docs: https://getcomposer.org/doc/articles/scripts.md

    # - name: Run test suite
    #   run: composer run-script test
