name: Tests

on: [pull_request]

jobs:
  php-cs-fixer:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          token: ${{ secrets.MOLLIE_TESTS}}

      - name: Run php-cs-fixer
        uses: docker://oskarstark/php-cs-fixer-ga

      - uses: stefanzweifel/git-auto-commit-action@v4
        with:
          commit_message: Apply php-cs-fixer changes

  test:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        php-versions: [ '7.1' ]

    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Pull PrestaShop files (Tag 1.7.7.0)
        run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:1.7.7.0

      - name: Run PHPunit
        run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module php:7.1-cli web/module/tests/phpunit.phar web/module/tests/Unit/ --bootstrap web/module/tests/Unit/bootstrap.php

  phpstan:
    name: PHPStan
    runs-on: ubuntu-latest
    strategy:
      matrix:
        presta-versions: ['1.7.6.8', '1.6.1.23', '1.7.7.0']
    steps:
      - name: Checkout
        uses: actions/checkout@v2.0.0

      - name: Pull PrestaShop files (Tag ${{ matrix.presta-versions }})
        run: docker run -tid --rm -v ps-volume:/var/www/html --name temp-ps prestashop/prestashop:${{ matrix.presta-versions }}

      - name : Run PHPStan
        run: docker run --rm --volumes-from temp-ps -v $PWD:/web/module -e _PS_ROOT_DIR_=/var/www/html --workdir=/web/module phpstan/phpstan:0.12 analyse --configuration=/web/module/tests/phpstan/phpstan${{ matrix.presta-versions }}.neon --debug --error-format github
